name: Deploy weblog content to omg.lol

# Runs on pushes targeting the "main" branch
on: 
  push:
    branches: ["main"]
jobs:
  weblog_import:
    runs-on: ubuntu-latest
    name: weblog.lol
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: mihobu
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
